### ISSUE TITLE
With `PullToRefresh` enabled ， if I use `CustomHeader`, 刷新中 和 刷新完成 时，第一列和其他列的行不同步

### ISSUE THREAD

**Issue by yingshaoxo** [MayLau-CbL/flutter_horizontal_data_table#49]
# demo
![20210604_161819](https://user-images.githubusercontent.com/17190829/120770254-88e9a080-c550-11eb-962f-4f8492de1b79.gif)

# code
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:horizontal_data_table/horizontal_data_table.dart';
import 'package:horizontal_data_table/refresh/pull_to_refresh/src/smart_refresher.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  HDTRefreshController _hdtRefreshController = HDTRefreshController();

  static const int sortName = 0;
  static const int sortStatus = 1;
  bool isAscending = true;
  int sortType = sortName;

  @override
  void initState() {
    user.initData(20);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: _getBodyWidget(),
    );
  }

  Widget _getBodyWidget() {
    return Container(
      child: HorizontalDataTable(
        leftHandSideColumnWidth: 100,
        rightHandSideColumnWidth: 600,
        isFixedHeader: true,
        headerWidgets: _getTitleWidget(),
        leftSideItemBuilder: _generateFirstColumnRow,
        rightSideItemBuilder: _generateRightHandSideColumnRow,
        itemCount: user.userInfo.length,
        rowSeparatorWidget: const Divider(
          color: Colors.black54,
          height: 1.0,
          thickness: 0.0,
        ),
        leftHandSideColBackgroundColor: Color(0xFFFFFFFF),
        rightHandSideColBackgroundColor: Color(0xFFFFFFFF),
        verticalScrollbarStyle: const ScrollbarStyle(
          thumbColor: Colors.yellow,
          isAlwaysShown: true,
          thickness: 0.0,
          radius: Radius.circular(5.0),
        ),
        horizontalScrollbarStyle: const ScrollbarStyle(
          thumbColor: Colors.red,
          isAlwaysShown: true,
          thickness: 0.0,
          radius: Radius.circular(5.0),
        ),
        enablePullToRefresh: true,
        refreshIndicator:
            /*
        const WaterDropHeader(),
        */
            CustomHeader(
          builder: (context, mode) {
            Widget body = Text("");
            if (mode == RefreshStatus.idle) {
              body = Text("pull down refresh");
            } else if (mode == RefreshStatus.refreshing) {
              body = CupertinoActivityIndicator();
            } else if (mode == RefreshStatus.canRefresh) {
              body = Text("release to refresh");
            } else if (mode == RefreshStatus.completed) {
              body = Text("refreshCompleted!");
            }
            return Container(
              height: 60.0,
              child: Center(
                child: body,
              ),
            );
          },
        ),
        refreshIndicatorHeight: 60,
        onRefresh: () async {
          //Do sth
          await Future.delayed(const Duration(milliseconds: 500));
          _hdtRefreshController.refreshCompleted();
        },
        htdRefreshController: _hdtRefreshController,
      ),
      height: MediaQuery.of(context).size.height,
    );
  }

  List<Widget> _getTitleWidget() {
    return [
      TextButton(
        style: TextButton.styleFrom(
          padding: EdgeInsets.zero,
        ),
        child: _getTitleItemWidget(
            'Name' + (sortType == sortName ? (isAscending ? '↓' : '↑') : ''),
            100),
        onPressed: () {
          sortType = sortName;
          isAscending = !isAscending;
          user.sortName(isAscending);
          setState(() {});
        },
      ),
      TextButton(
        style: TextButton.styleFrom(
          padding: EdgeInsets.zero,
        ),
        child: _getTitleItemWidget(
            'Status' +
                (sortType == sortStatus ? (isAscending ? '↓' : '↑') : ''),
            100),
        onPressed: () {
          sortType = sortStatus;
          isAscending = !isAscending;
          user.sortStatus(isAscending);
          setState(() {});
        },
      ),
      _getTitleItemWidget('Phone', 200),
      _getTitleItemWidget('Register', 100),
      _getTitleItemWidget('Termination', 200),
    ];
  }

  Widget _getTitleItemWidget(String label, double width) {
    return Container(
      child: Text(label, style: TextStyle(fontWeight: FontWeight.bold)),
      width: width,
      height: 56,
      padding: EdgeInsets.fromLTRB(5, 0, 0, 0),
      alignment: Alignment.centerLeft,
    );
  }

  Widget _generateFirstColumnRow(BuildContext context, int index) {
    return Container(
      child: Text(user.userInfo[index].name),
      width: 100,
      height: 52,
      padding: EdgeInsets.fromLTRB(5, 0, 0, 0),
      alignment: Alignment.centerLeft,
    );
  }

  Widget _generateRightHandSideColumnRow(BuildContext context, int index) {
    return Row(
      children: <Widget>[
        Container(
          child: Row(
            children: <Widget>[
              Icon(
                  user.userInfo[index].status
                      ? Icons.notifications_off
                      : Icons.notifications_active,
                  color:
                      user.userInfo[index].status ? Colors.red : Colors.green),
              Text(user.userInfo[index].status ? 'Disabled' : 'Active')
            ],
          ),
          width: 100,
          height: 52,
          padding: EdgeInsets.fromLTRB(5, 0, 0, 0),
          alignment: Alignment.centerLeft,
        ),
        Container(
          child: Text(user.userInfo[index].phone),
          width: 200,
          height: 52,
          padding: EdgeInsets.fromLTRB(5, 0, 0, 0),
          alignment: Alignment.centerLeft,
        ),
        Container(
          child: Text(user.userInfo[index].registerDate),
          width: 100,
          height: 52,
          padding: EdgeInsets.fromLTRB(5, 0, 0, 0),
          alignment: Alignment.centerLeft,
        ),
        Container(
          child: Text(user.userInfo[index].terminationDate),
          width: 200,
          height: 52,
          padding: EdgeInsets.fromLTRB(5, 0, 0, 0),
          alignment: Alignment.centerLeft,
        ),
      ],
    );
  }
}

User user = User();

class User {
  List<UserInfo> userInfo = [];

  void initData(int size) {
    for (int i = 0; i < size; i++) {
      userInfo.add(UserInfo(
          "User_$i", i % 3 == 0, '+001 9999 9999', '2019-01-01', 'N/A'));
    }
  }

  ///
  /// Single sort, sort Name's id
  void sortName(bool isAscending) {
    userInfo.sort((a, b) {
      int aId = int.tryParse(a.name.replaceFirst('User_', '')) ?? 0;
      int bId = int.tryParse(b.name.replaceFirst('User_', '')) ?? 0;
      return (aId - bId) * (isAscending ? 1 : -1);
    });
  }

  ///
  /// sort with Status and Name as the 2nd Sort
  void sortStatus(bool isAscending) {
    userInfo.sort((a, b) {
      if (a.status == b.status) {
        int aId = int.tryParse(a.name.replaceFirst('User_', '')) ?? 0;
        int bId = int.tryParse(b.name.replaceFirst('User_', '')) ?? 0;
        return (aId - bId);
      } else if (a.status) {
        return isAscending ? 1 : -1;
      } else {
        return isAscending ? -1 : 1;
      }
    });
  }
}

class UserInfo {
  String name;
  bool status;
  String phone;
  String registerDate;
  String terminationDate;

  UserInfo(this.name, this.status, this.phone, this.registerDate,
      this.terminationDate);
}
```

**Comment by yingshaoxo** [comment]
@cblmay0413 

Demonstrated code updated, please consider fixing it.

Since this is a basic usage from the example code.

**Comment by yingshaoxo** [comment]
So far, as I tested out, only `ClassHeader` and `WaterDropHeader` works without any problem.

Unfortunately, the `TwoLevelHeader`, `BezierHeader`, and `MaterialClassicHeader` would have the same problem as I described above.

Again, please at least fix the `CustomHeader`.

**Comment by MayLau-CbL** [comment]
Hi @yingshaoxo ! I have released a new version 3.4.0 which is mainly updated the vertical scroll offset synchronization logic. Since the scroll offset synchronization is relied on the scroll notification, the scroll on the left and right may have slightly different on the offset sometimes. This update aims to soften the problem especially when it comes to pull to refresh. You may try to see if this may help you.

**Comment by yingshaoxo** [comment]
> Hi @yingshaoxo ! I have released a new version 3.4.0 which is mainly updated the vertical scroll offset synchronization logic. Since the scroll offset synchronization is relied on the scroll notification, the scroll on the left and right may have slightly different on the offset sometimes. This update aims to soften the problem especially when it comes to pull to refresh. You may try to see if this may help you.

Sorry to let you know that, it's getting even worse after the update.

![20210606_113341](https://user-images.githubusercontent.com/17190829/120911613-54debe80-c6bb-11eb-8e2f-86e525f670d8.gif)

https://github.com/MayLau-CbL/flutter_horizontal_data_table/blob/master/example/lib/main.dart

**One interesting fact is that you can even run that example at brower. You'll still see the bad result as above gif shows.**

My flutter version is: 
```
Flutter 2.0.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1d9032c7e1 (5 weeks ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3
```

**Comment by yingshaoxo** [comment]
@MayLau-CbL 

Hi, there!

Here's good news for us. As I tested out, you just have to change one line of codes to make it work:

```dart
// https://github.com/MayLau-CbL/flutter_horizontal_data_table/blob/master/lib/scroll/sync_scroll_controller_manager.dart#L81

  void _syncLeftListViewScrollVontroller(
      ScrollController _scrollingController, ScrollController controller) {
    log(_refreshController!.headerStatus.toString());

    if (_refreshController?.headerStatus != null) {
      switch (_refreshController?.headerStatus) {
        case RefreshStatus.canRefresh:
          {
            // You need to change something in here
            break;
          }
        case RefreshStatus.refreshing:
          {
            controller.jumpTo(_refreshIndicatorHeight * -1);
            break;
          }
        default:
          {
            if (_scrollingController.offset < (_refreshIndicatorHeight * -1)) {
              controller.jumpTo(_refreshIndicatorHeight * -1);
            } else {
              controller.jumpTo(_scrollingController.offset);
            }
            break;
          }
      }
    } else {
      controller.jumpTo(_scrollingController.offset);
    }
  }
```

Since I'm not very familiar to flutter, so it's only possible for you to solve it.

Looking forward to your solution (good luck

**Comment by yingshaoxo** [comment]
I solved the problem.

I'll do a pull later.

**Comment by yingshaoxo** [comment]
> I solved the problem.
> 
> I'll do a pull later.

I did a pull. 

Please take a review or edition, then merge. (I forgot to increase the version number, I don't know if it matters.
